In [1]:
!pip install tensorflow==2.0.0



     |████████████████████████████████| 86.3MB 52kB/s 
     |████████████████████████████████| 450kB 69.9MB/s 
     |████████████████████████████████| 3.8MB 29.3MB/s 
     |████████████████████████████████| 81kB 12.8MB/s 
ERROR: tensorboard 2.0.2 has requirement grpcio>=1.24.3, but you'll have grpcio 1.15.0 which is incompatible.
ERROR: google-colab 1.0.0 has requirement google-auth~=1.4.0, but you'll have google-auth 1.11.0 which is incompatible.
  Found existing installation: tensorflow-estimator 1.15.1
    Uninstalling tensorflow-estimator-1.15.1:
      Successfully uninstalled tensorflow-estimator-1.15.1
  Found existing installation: google-auth 1.4.2
    Uninstalling google-auth-1.4.2:
      Successfully uninstalled google-auth-1.4.2
  Found existing installation: tensorboard 1.15.0
    Uninstalling tensorboard-1.15.0:
      Successfully uninstalled tensorboard-1.15.0
  Found existing installation: tensorflow 1.15.0
    Uninstalling tensorflow-1.15.0:
      Successfully uninstall

In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
print(tf.__version__)

2.0.0


In [2]:
dataset = tf.data.Dataset.range(20)
for val in dataset:
   print(val.numpy())

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [4]:
dataset = tf.data.Dataset.range(20)
dataset = dataset.window(6, shift=1)
for window_dataset in dataset:
  for val in window_dataset:
    print(val.numpy(), end=" ")
  print()

0 1 2 3 4 5 
1 2 3 4 5 6 
2 3 4 5 6 7 
3 4 5 6 7 8 
4 5 6 7 8 9 
5 6 7 8 9 10 
6 7 8 9 10 11 
7 8 9 10 11 12 
8 9 10 11 12 13 
9 10 11 12 13 14 
10 11 12 13 14 15 
11 12 13 14 15 16 
12 13 14 15 16 17 
13 14 15 16 17 18 
14 15 16 17 18 19 
15 16 17 18 19 
16 17 18 19 
17 18 19 
18 19 
19 


In [6]:
dataset = tf.data.Dataset.range(20)
dataset = dataset.window(5, shift=1, drop_remainder=True)
for window_dataset in dataset:
  for val in window_dataset:
    print(val.numpy(), end=" ")
  print()

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 
6 7 8 9 10 
7 8 9 10 11 
8 9 10 11 12 
9 10 11 12 13 
10 11 12 13 14 
11 12 13 14 15 
12 13 14 15 16 
13 14 15 16 17 
14 15 16 17 18 
15 16 17 18 19 


In [9]:
dataset = tf.data.Dataset.range(20)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(6))
for window in dataset:
  print(window.numpy())


[0 1 2 3 4]
[1 2 3 4 5]
[2 3 4 5 6]
[3 4 5 6 7]
[4 5 6 7 8]
[5 6 7 8 9]
[ 6  7  8  9 10]
[ 7  8  9 10 11]
[ 8  9 10 11 12]
[ 9 10 11 12 13]
[10 11 12 13 14]
[11 12 13 14 15]
[12 13 14 15 16]
[13 14 15 16 17]
[14 15 16 17 18]
[15 16 17 18 19]


In [11]:
dataset = tf.data.Dataset.range(20)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
for x,y in dataset:
  print(x.numpy(), y.numpy())

[0 1 2 3] [4]
[1 2 3 4] [5]
[2 3 4 5] [6]
[3 4 5 6] [7]
[4 5 6 7] [8]
[5 6 7 8] [9]
[6 7 8 9] [10]
[ 7  8  9 10] [11]
[ 8  9 10 11] [12]
[ 9 10 11 12] [13]
[10 11 12 13] [14]
[11 12 13 14] [15]
[12 13 14 15] [16]
[13 14 15 16] [17]
[14 15 16 17] [18]
[15 16 17 18] [19]


In [12]:
dataset = tf.data.Dataset.range(20)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
dataset = dataset.shuffle(buffer_size=10)
for x,y in dataset:
  print(x.numpy(), y.numpy())


[ 9 10 11 12] [13]
[2 3 4 5] [6]
[ 8  9 10 11] [12]
[3 4 5 6] [7]
[6 7 8 9] [10]
[12 13 14 15] [16]
[14 15 16 17] [18]
[13 14 15 16] [17]
[10 11 12 13] [14]
[0 1 2 3] [4]
[5 6 7 8] [9]
[15 16 17 18] [19]
[1 2 3 4] [5]
[ 7  8  9 10] [11]
[11 12 13 14] [15]
[4 5 6 7] [8]


In [14]:
dataset = tf.data.Dataset.range(20)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
dataset = dataset.shuffle(buffer_size=10)
dataset = dataset.batch(2).prefetch(1)
for x,y in dataset:
  print("x = ", x.numpy())
  print("y = ", y.numpy())


x =  [[6 7 8 9]
 [1 2 3 4]]
y =  [[10]
 [ 5]]
x =  [[11 12 13 14]
 [ 4  5  6  7]]
y =  [[15]
 [ 8]]
x =  [[ 5  6  7  8]
 [10 11 12 13]]
y =  [[ 9]
 [14]]
x =  [[ 2  3  4  5]
 [ 7  8  9 10]]
y =  [[ 6]
 [11]]
x =  [[15 16 17 18]
 [ 8  9 10 11]]
y =  [[19]
 [12]]
x =  [[12 13 14 15]
 [ 9 10 11 12]]
y =  [[16]
 [13]]
x =  [[3 4 5 6]
 [0 1 2 3]]
y =  [[7]
 [4]]
x =  [[13 14 15 16]
 [14 15 16 17]]
y =  [[17]
 [18]]
